### ISSUE TITLE
Migration from version 3.0.0

### ISSUE THREAD

**Issue by ricardoboss** [ctolkien/Slugify#65]
Hi! Thanks for maintaining this project!

I saw there was an update available today and wanted to read up on what has changed, but the releases here on github are a bit... cryptic. The release notes for https://github.com/ctolkien/Slugify/releases/tag/Release-v4 mention multiple versions. I guess these are changes that have not been included in a release yet, so GitHub automatically put them there.

Release https://github.com/ctolkien/Slugify/releases/tag/Release-v4.0.1 seems to just update some dependencies.

Is there any migration guide for updating from 3.0.0 to 4.0.1?

Also, I cannot find any tag that points to the rev which represents version 3.0.0. Can you add it?

**Comment by ctolkien** [comment]
Release notes are now autogenerated since the last tag - of which there are none, so it includes everything! That will fix itself up going forward. This is actually just a minor bug fix release specifically to address https://github.com/ctolkien/Slugify/issues/52, but we also updated some of our dependency major versions, so out of caution just decided to do a major version bump for us as well. 

The API surface is the same, there shouldn't be any migration needed.

V3 is here (no actually tag against that at the moment):

https://github.com/ctolkien/Slugify/commit/ffadd4486a5bfff877a6fd96469388eb3bf9a70b

**Comment by ricardoboss** [comment]
Thanks for clearing things up for me!

Again, thanks for maintaining this project.
